# Generated by Django 3.2.19 on 2023-06-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranq_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.CharField(choices=[('ongoing', 'ongoing'), ('completed', 'completed')], default='ongoing', max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='type',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=50),
        ),
    ]
