# Generated by Django 3.2.19 on 2023-06-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranq_app', '0002_auto_20230620_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-created_at']},
        ),
    ]
