# Generated by Django 3.2.19 on 2023-06-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranq_app', '0003_alter_poll_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='privatevoter',
            name='token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emailtoken',
            name='type',
            field=models.CharField(choices=[('ongoing', 'ongoing'), ('completed', 'completed')], default='signup_email', max_length=50),
        ),
    ]
