# Generated by Django 3.2.19 on 2023-06-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranq_app', '0004_auto_20230622_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='type',
            field=models.CharField(choices=[('signup_email', 'signup_email'), ('vote_email', 'vote_email'), ('forgot_password', 'forgot_password')], default='signup_email', max_length=50),
        ),
    ]
