# Generated by Django 3.2.19 on 2023-06-22 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranq_app', '0005_alter_emailtoken_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='poll_id',
            field=models.ForeignKey(default='f54f3581-227d-4d80-b3d2-4adbd4d5b48f', on_delete=django.db.models.deletion.CASCADE, to='ranq_app.poll'),
        ),
        migrations.AddField(
            model_name='voter',
            name='token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voter',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
