# Generated by Django 3.2.19 on 2023-06-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranq_app', '0006_auto_20230622_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
