# Generated by Django 3.2.19 on 2023-06-22 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranq_app', '0007_alter_voter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='poll_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranq_app.poll'),
        ),
    ]
